//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t auth(int32_t a1, int32_t a2);

// --------------------- Global Variables ---------------------

char * g1 = "\x1b\x5b\x33\x32\x6d\x2e\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2e"; // 0x8048a68
int32_t g2 = 0x31335b1b; // 0x8048a8c
int32_t g3 = 0x32335b1b; // 0x8048ab0
struct _IO_FILE * g4 = NULL; // 0x804a060

// ------------------------ Functions -------------------------

// Address range: 0x8048748 - 0x8048878
int32_t auth(int32_t a1, int32_t a2) {
    char * str = (char *)a1;
    *(char *)(strcspn(str, "\n") + a1) = 0;
    int32_t v1 = strnlen(str, 32); // 0x8048775
    if (v1 == 0) {
        // 0x8048785
        // branch -> 0x804878c
    } else {
        // 0x8048785
        if (v1 > 5) {
            // 0x8048796
            if (ptrace(0) == -1) {
                // 0x80487bf
                puts((char *)&g1);
                puts((char *)&g2);
                puts((char *)&g3);
                // branch -> 0x8048877
                // 0x8048877
                return 1;
            }
            int32_t v2 = 0;
            int32_t v3 = ((int32_t)*(char *)(a1 + 3) ^ 0x1337) + 0x5eeded; // 0x80488662126
            // branch -> 0x804880f
            int32_t v4; // 0x8048854
            while (true) {
                char * v5 = (char *)(v2 + a1);
                if (*v5 <= 31) {
                    // 0x804881c
                    // branch -> 0x8048877
                    // 0x8048877
                    return 1;
                }
                int32_t v6 = (int32_t)*v5 ^ v3; // 0x8048831
                int32_t v7 = 0x88233b2b * (int64_t)v6 / 0x100000000; // 0x804883b
                v4 = v6 + -1337 * ((v6 - v7) / 2 + v7) / 1024 + v3;
                int32_t v8 = v2 + 1; // 0x8048857
                if (v8 >= v1) {
                    // break -> 0x8048863
                    break;
                }
                v2 = v8;
                v3 = v4;
                // continue -> 0x804880f
            }
            // 0x8048863
            int32_t result; // 0x8048878_2
            if (v4 == a2) {
                // 0x8048872
                result = 0;
                // branch -> 0x8048877
            } else {
                // 0x804886b
                result = 1;
                // branch -> 0x8048877
            }
            // 0x8048877
            return result;
        }
    }
    // 0x804878c
    // branch -> 0x8048877
    // 0x8048877
    return 1;
}

// Address range: 0x8048879 - 0x804898f
int main(int argc, char ** argv) {
    puts("***********************************");
    puts("*\t\tlevel06\t\t  *");
    puts("***********************************");
    printf("-> Enter Login: ");
    int32_t str;
    fgets((char *)&str, 32, g4);
    puts("***********************************");
    puts("***** NEW ACCOUNT DETECTED ********");
    puts("***********************************");
    printf("-> Enter Serial: ");
    int32_t v1;
    scanf("%u", &v1);
    int32_t v2 = auth((int32_t)&str, v1); // 0x8048941
    int32_t result = 1;
    if (v2 == 0) {
        // 0x804894a
        puts("Authenticated!");
        system("/bin/sh");
        result = 0;
        // branch -> 0x804896e
    }
    // 0x804896e
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x804897b
        __stack_chk_fail();
        // branch -> 0x8048980
    }
    // 0x8048980
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// int printf(const char * restrict format, ...);
// long int ptrace(enum __ptracerequest __request, ...);
// int puts(const char * s);
// int scanf(const char * restrict format, ...);
// size_t strcspn(const char * s, const char * reject);
// size_t strnlen(const char * string, size_t maxlen);
// int system(const char * command);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-10-06 14:09:31
